# Generated by Django 4.2.27 on 2026-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_entry",
            name="Corr_District",
            field=models.CharField(default="not available", max_length=50),
        ),
        migrations.AlterField(
            model_name="user_entry",
            name="Corr_Pin",
            field=models.CharField(default="not available", max_length=20),
        ),
        migrations.AlterField(
            model_name="user_entry",
            name="Corr_State",
            field=models.CharField(default="not available", max_length=50),
        ),
        migrations.AlterField(
            model_name="user_entry",
            name="corr_address",
            field=models.CharField(default="not available", max_length=500),
        ),
    ]
