# Generated by Django 4.2.27 on 2026-02-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0003_category_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="category_entry",
        ),
    ]
