# Generated by Django 4.2.27 on 2026-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0005_category_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="supplier_entry",
            fields=[
                ("Entry_date", models.DateField(auto_now_add=True)),
                (
                    "Supplier_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Contact_Number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("GST_Number", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="user_payment",
            fields=[
                ("Payment_Date", models.DateField(auto_now_add=True)),
                (
                    "Payment_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("User_ID", models.CharField(max_length=50)),
                ("Amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
    ]
