# Generated by Django 4.2.27 on 2026-02-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0006_supplier_entry_user_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer_entry",
            fields=[
                ("Created_at", models.DateField(auto_now_add=True)),
                (
                    "Customer_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Contact_number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Order_entry",
            fields=[
                (
                    "Order_Item_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Order_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Price", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("Sub_total", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order_payment_entry",
            fields=[
                ("Payment_date", models.DateField(auto_now_add=True)),
                (
                    "Payment_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Order_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Paid_amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("Remark", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="product_entry",
            fields=[
                ("Entry_date", models.DateField(auto_now_add=True)),
                (
                    "Product_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Product_Name", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="purchase_entry",
            fields=[
                ("Purchase_date", models.DateField(auto_now_add=True)),
                (
                    "Purchase_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Total_amount", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="purchase_item_entry",
            fields=[
                ("Purchase_date", models.DateField(auto_now_add=True)),
                (
                    "Purchase_Item_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Purchase_unit_price", models.CharField(max_length=50)),
                ("Unit_price", models.CharField(max_length=50)),
                ("Sell_price", models.CharField(max_length=50)),
                ("Gross_amount", models.CharField(max_length=50)),
            ],
        ),
    ]
