# Generated by Django 4.2.27 on 2026-02-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "GroceryPrivate",
            "0007_customer_entry_order_entry_order_payment_entry_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order_entry",
        ),
        migrations.DeleteModel(
            name="Order_payment_entry",
        ),
    ]
