# Generated by Django 4.2.27 on 2026-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0008_delete_order_entry_delete_order_payment_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_entry",
            fields=[
                ("Order_date", models.DateField(auto_now_add=True)),
                (
                    "Order_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("User_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Amount", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("tax", models.CharField(max_length=50)),
                ("pay_amount", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="order_item_entry",
            fields=[
                (
                    "Order_Item_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Order_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Price", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("Sub_total", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order_payment_entry",
            fields=[
                ("Payment_date", models.DateField(auto_now_add=True)),
                (
                    "Payment_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Order_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Paid_amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("Remark", models.CharField(max_length=500)),
            ],
        ),
    ]
