# Generated by Django 4.2.27 on 2026-02-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0009_order_entry_order_item_entry_order_payment_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_entry",
        ),
    ]
