# Generated by Django 4.2.27 on 2026-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0010_delete_user_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_entry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Joining_date", models.DateField(auto_now_add=True)),
                ("User_ID", models.IntegerField(default=None, null=True, unique=True)),
                ("Name", models.CharField(max_length=100)),
                ("Father_name", models.CharField(max_length=100)),
                ("Mother_name", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=50)),
                ("DOB", models.DateField()),
                ("contact_number", models.CharField(max_length=20)),
                ("Alternate_number", models.CharField(max_length=20)),
                ("Email_ID", models.EmailField(max_length=100)),
                ("aadhaar_number", models.CharField(max_length=100)),
                ("highest_qualifiication", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("pin", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=500)),
                (
                    "Corr_State",
                    models.CharField(default="not available", max_length=50),
                ),
                (
                    "Corr_District",
                    models.CharField(default="not available", max_length=50),
                ),
                ("Corr_Pin", models.CharField(default="not available", max_length=20)),
                (
                    "corr_address",
                    models.CharField(default="not available", max_length=500),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "aadhaar_pic",
                    models.ImageField(blank=True, null=True, upload_to="aadhaar/"),
                ),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                (
                    "certificate",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
            ],
        ),
    ]
