# Generated by Django 4.2.27 on 2026-02-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0012_alter_user_entry_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_payment",
        ),
    ]
