# Generated by Django 4.2.27 on 2026-02-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0013_delete_user_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_payment",
            fields=[
                ("Payment_Date", models.DateField(auto_now_add=True)),
                (
                    "Payment_ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                (
                    "User_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="GroceryPrivate.user_entry",
                    ),
                ),
            ],
        ),
    ]
