# Generated by Django 4.2.27 on 2026-02-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0014_user_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_payment",
            name="User_ID",
        ),
        migrations.DeleteModel(
            name="user_entry",
        ),
        migrations.DeleteModel(
            name="user_payment",
        ),
    ]
