# Generated by Django 4.2.27 on 2026-02-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0022_user_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_payment",
        ),
    ]
