# Generated by Django 4.2.27 on 2026-02-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0030_user_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="category_entry",
        ),
    ]
