# Generated by Django 4.2.27 on 2026-02-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0034_category_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="supplier_entry",
        ),
    ]
