# Generated by Django 4.2.27 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0035_delete_supplier_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="supplier_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Entry_date", models.DateField(auto_now=True)),
                ("Supplier_ID", models.CharField(max_length=50, unique=True)),
                ("Name", models.CharField(max_length=50)),
                ("Contact_Number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("GST_Number", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
    ]
