# Generated by Django 4.2.27 on 2026-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0037_delete_product_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Entry_date", models.DateField(auto_now=True)),
                ("Product_ID", models.CharField(max_length=50, unique=True)),
                ("Product_Name", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
    ]
