# Generated by Django 4.2.27 on 2026-02-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0038_product_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="purchase_item_entry",
        ),
    ]
