# Generated by Django 4.2.27 on 2026-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0039_delete_purchase_item_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="purchase_item_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Purchase_date", models.DateField(auto_now=True)),
                ("Purchase_Item_ID", models.CharField(max_length=50, unique=True)),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Purchase_unit_price", models.CharField(max_length=50)),
                ("Unit_price", models.CharField(max_length=50)),
                ("Sell_price", models.CharField(max_length=50)),
                ("Gross_amount", models.CharField(max_length=50)),
            ],
        ),
    ]
