# Generated by Django 4.2.27 on 2026-02-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0040_purchase_item_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="purchase_entry",
        ),
    ]
