# Generated by Django 4.2.27 on 2026-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0041_delete_purchase_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="purchase_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Purchase_date", models.DateField(auto_now=True)),
                ("Purchase_ID", models.CharField(max_length=50, unique=True)),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Total_amount", models.CharField(max_length=50)),
            ],
        ),
    ]
