# Generated by Django 4.2.27 on 2026-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0043_delete_customer_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created_at", models.DateField(auto_now=True)),
                ("Customer_ID", models.CharField(max_length=50, unique=True)),
                ("Name", models.CharField(max_length=100)),
                ("Contact_number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
    ]
