# Generated by Django 4.2.27 on 2026-02-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0044_customer_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order_entry",
        ),
        migrations.DeleteModel(
            name="order_item_entry",
        ),
        migrations.DeleteModel(
            name="Order_payment_entry",
        ),
    ]
