# Generated by Django 4.2.27 on 2026-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0045_delete_order_entry_delete_order_item_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_date", models.DateField(auto_now_add=True)),
                ("Order_ID", models.CharField(max_length=50, unique=True)),
                ("User_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Amount", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("tax", models.CharField(max_length=50)),
                ("pay_amount", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="order_item_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_Item_ID", models.CharField(max_length=50, unique=True)),
                ("Order_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Price", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("Sub_total", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order_payment_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Payment_date", models.DateField(auto_now_add=True)),
                ("Payment_ID", models.CharField(max_length=50, unique=True)),
                ("Order_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Paid_amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("Remark", models.CharField(max_length=500)),
            ],
        ),
    ]
