# Generated by Django 4.2.27 on 2026-02-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0046_order_entry_order_item_entry_order_payment_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="category_entry",
        ),
    ]
