# Generated by Django 4.2.27 on 2026-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0047_delete_category_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="category_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Entry_date", models.DateField(auto_now=True)),
                ("Category_ID", models.IntegerField(unique=True)),
                ("Category_name", models.CharField(max_length=50)),
                ("User_ID", models.CharField(max_length=50)),
                ("Order_ID", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=20)),
                ("Description", models.CharField(max_length=500)),
            ],
        ),
    ]
