# Generated by Django 4.2.27 on 2026-02-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0048_category_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customer_entry",
        ),
        migrations.DeleteModel(
            name="order_entry",
        ),
        migrations.DeleteModel(
            name="order_item_entry",
        ),
        migrations.DeleteModel(
            name="Order_payment_entry",
        ),
        migrations.DeleteModel(
            name="product_entry",
        ),
        migrations.DeleteModel(
            name="purchase_entry",
        ),
        migrations.DeleteModel(
            name="purchase_item_entry",
        ),
        migrations.DeleteModel(
            name="supplier_entry",
        ),
    ]
