# Generated by Django 4.2.27 on 2026-02-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0049_delete_customer_entry_delete_order_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created_at", models.DateField(auto_now=True)),
                ("Customer_ID", models.CharField(max_length=50, unique=True)),
                ("Name", models.CharField(max_length=100)),
                ("Contact_number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="order_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_date", models.DateField(auto_now_add=True)),
                ("Order_ID", models.CharField(max_length=50, unique=True)),
                ("User_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Amount", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("tax", models.CharField(max_length=50)),
                ("pay_amount", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="order_item_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_Item_ID", models.CharField(max_length=50, unique=True)),
                ("Order_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Price", models.CharField(max_length=50)),
                ("Disc_amount", models.CharField(max_length=50)),
                ("Sub_total", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order_payment_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Payment_date", models.DateField(auto_now_add=True)),
                ("Payment_ID", models.CharField(max_length=50, unique=True)),
                ("Order_ID", models.CharField(max_length=50)),
                ("Customer_ID", models.CharField(max_length=50)),
                ("Paid_amount", models.CharField(max_length=50)),
                ("Payment_mode", models.CharField(max_length=50)),
                ("Balance", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("Remark", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="product_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Entry_date", models.DateField(auto_now=True)),
                ("Product_ID", models.CharField(max_length=50, unique=True)),
                ("Product_Name", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="purchase_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Purchase_date", models.DateField(auto_now=True)),
                ("Purchase_ID", models.CharField(max_length=50, unique=True)),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Total_amount", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="purchase_item_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Purchase_date", models.DateField(auto_now=True)),
                ("Purchase_Item_ID", models.CharField(max_length=50, unique=True)),
                ("Supplier_ID", models.CharField(max_length=50)),
                ("Category_ID", models.CharField(max_length=50)),
                ("Product_ID", models.CharField(max_length=50)),
                ("Quantity", models.CharField(max_length=50)),
                ("Purchase_unit_price", models.CharField(max_length=50)),
                ("Unit_price", models.CharField(max_length=50)),
                ("Sell_price", models.CharField(max_length=50)),
                ("Gross_amount", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="supplier_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Entry_date", models.DateField(auto_now=True)),
                ("Supplier_ID", models.CharField(max_length=50, unique=True)),
                ("Name", models.CharField(max_length=50)),
                ("Contact_Number", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("GST_Number", models.CharField(max_length=50)),
                ("Status", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("District", models.CharField(max_length=50)),
                ("Pin", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=500)),
            ],
        ),
    ]
