# Generated by Django 4.2.27 on 2026-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroceryPrivate", "0050_customer_entry_order_entry_order_item_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="state",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
